### ISSUE TITLE
DaliConfig.cmake typo

### ISSUE THREAD

**Issue by byzhang** [dali-ml/Dali#12]
When I build dali-examples, it shows the following error
```
CMake Warning (dev) at CMakeLists.txt:12 (find_package):
  A logical block opening on the line

    /usr/lib/dali/cmake/DaliConfig.cmake:54 (if)

  closes on the line

    /usr/lib/dali/cmake/DaliConfig.cmake:84 (endif)

  with mis-matching arguments.
```
It seems the DALI_CORE_LIBRARIES should be DALI_LIBRARIES

**Comment by nivwusquorum** [comment]
Thanks amazing, thanks a lot for reporting this. It should be fixed now.

btw. if you don't mind me asking. I am really curious how are you using Dali? Are you just checking it out or do you have a project? 

btw2. We have a new and reimagined version of Dali coming out in the near future, with ND Tensors and convolution support, so stay tuned!

**Comment by byzhang** [comment]
Yes, I'd love to use it in real projects.

Thanks,
-B
